services:
  web:
    build: .
    container_name: anime-app
    ports:
      - "8080:80"
    restart: unless-stopped

  api:
    build: ./api
    container_name: anime-api
    expose:
      - "5000"
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

volumes:
  portainer_data:
